### ISSUE TITLE
No deberían tener efecto acá

### ISSUE THREAD

**Issue by julian-berbel** [mackhood/tp-objetos-lose-spinelli-jugo#3]
https://github.com/mackhood/tp-objetos-lose-spinelli-jugo/blob/54bed54553082c09519ce14054977f76d9ffbf0b/src/artistas.wlk#L9-L19

Si canta sólo su habilidad es de 20 y si canta en grupo es de 25. No va aumentando más con el tiempo.

**Comment by julian-berbel** [comment]
Idem acá:
https://github.com/mackhood/tp-objetos-lose-spinelli-jugo/blob/54bed54553082c09519ce14054977f76d9ffbf0b/src/artistas.wlk#L37-L47

**Comment by mackhood** [comment]
method cantaPresentacion (unaPresentacion) { 
 if( unaPresentacion.hayUnoSolo() ) 
      {   habilidad=25
              } 
 else { habilidad  
 }  } 
method cantaPresentacion (unaPresentacion) { 
 if( unaPresentacion.hayUnoSolo() ) 
      {   habilidad=50
              } 
 else { return habilidad  
 }  } 

Serviria esta solucion ya que si modificariamos la habiliadad de estos artistas ya no servirira pero como el enunciado no especifica nada ?

**Comment by julian-berbel** [comment]
subí la solución directo y si esta mal puedo reabrir el issue, si pones el código en texto plano no puedo marcarlo o/

No hace falta que asignes ninguna variable. Podes retornar el valor que corresponde nomas.
