### ISSUE TITLE
Cambiar métodos para cada guitarra por WKOs y polimorfismo

### ISSUE THREAD

**Issue by julian-berbel** [mackhood/tp-objetos-lose-spinelli-jugo#4]
https://github.com/mackhood/tp-objetos-lose-spinelli-jugo/blob/54bed54553082c09519ce14054977f76d9ffbf0b/src/artistas.wlk#L69-L78

**Comment by mackhood** [comment]
object luisAlberto {
....

method valorGuitarra(unaGuitarra,estado){
return unaGuitarra.valor(estado)
}
}


object gibson { 
var valor=10
 
method valor(estado){
return valor}

object fender {
var valor=15 
method valor(estado) {
if (estado =="rota"){
valor= 5
return valor
}
else return valor
}}
Serviria esto?Saludos

**Comment by julian-berbel** [comment]
No le deberías pasar el estado se su guitarra al artista, eso lo debería conocer la guitarra directamente.

Sería mejor que el estado de la guitarra no sea un String sino un valor booleano (e.g. estaEnBuenEstado, o estaRota)
