### ISSUE TITLE
Las fechas de wollok son comparables por < y >

### ISSUE THREAD

**Issue by julian-berbel** [mackhood/tp-objetos-lose-spinelli-jugo#7]
https://github.com/mackhood/tp-objetos-lose-spinelli-jugo/blob/54bed54553082c09519ce14054977f76d9ffbf0b/src/Presentaciones.wlk#L20

**Comment by julian-berbel** [comment]
btw, laFecha no existe en este scope

**Comment by mackhood** [comment]
que habria que usar la variable fecha  return fecha>= ultimoDiaSeptiembre ? o pasarle por parametro unaPresentacion y ademas hacer un getter de fecha y  compararlo unaPresentacion.fecha() <=(ultimoDiaSeptiembre)

cons ultimoDiaSeptiembre = new Date (30,09,17).
Saludos

**Comment by julian-berbel** [comment]
podrías hacerle un método que dada una fecha te diga si esa presentación es antes de ella y pasarle por parámetro el primer día de octubre. Así tendrías mejor asignadas las responsabilidades ya que el que sea hasta septiembre es algo inherente al artista y no a la presentación
