### ISSUE TITLE
Lo que necesitan acá es un .sum(), no un .fold()

### ISSUE THREAD

**Issue by julian-berbel** [mackhood/tp-objetos-lose-spinelli-jugo#8]
https://github.com/mackhood/tp-objetos-lose-spinelli-jugo/blob/54bed54553082c09519ce14054977f76d9ffbf0b/src/Presentaciones.wlk#L32

Y recuerden de Haskell que fold aplana una lista con una función que toma dos parámetros!
En este caso con un fold se haría:

`artistas.fold(0, {acumulador, unArtista => unArtista.cobra(self) + acumulador})`

De todos modos, en este caso el .sum() es una abstracción mucho más apropiada.

**Comment by julian-berbel** [comment]
https://github.com/mackhood/tp-objetos-lose-spinelli-jugo/blob/54bed54553082c09519ce14054977f76d9ffbf0b/src/Presentaciones.wlk#L6
esta variable les va a quedar de más

**Comment by mackhood** [comment]
return artistas.sum({unArtista=> unArtista.cobra(self)})   estaría bien así?

**Comment by julian-berbel** [comment]
si que si
