### ISSUE TITLE
La capacidad es de 700 sólo los sábados

### ISSUE THREAD

**Issue by julian-berbel** [mackhood/tp-objetos-lose-spinelli-jugo#9]
https://github.com/mackhood/tp-objetos-lose-spinelli-jugo/blob/54bed54553082c09519ce14054977f76d9ffbf0b/src/programa.wpgm#L16

Las fechas entienden el mensaje .dayOfWeek()

**Comment by mackhood** [comment]
object laTrastienda inherits Presentacion  (700, fechaTrastienda , #{luisAlberto,joaquin,lucia} ) {
  method capadicad(){
  if ( fechaTrastienda.dayOfweek == 6){
  
  capacidad=700
  }
  else { 
  capacidad=300
  }
  }
  
  }

Hola juli  serviria esta solucion?Saludos

**Comment by julian-berbel** [comment]
:+1:
